### ISSUE TITLE
Cannot read property 'ref' of undefined

### ISSUE THREAD

**Issue by lobor** [materik/restberry#4]
Hi,

I have this schema, 
```javascript
{
        name: {
    		type: String,
    		required: true,
    		index: {
    			unique: true
    		}
    	},
        rcs: {
    		type: Number,
    		required: true
    	},
        date_immatriculation: {
    		type: Date,
    		required: true
    	},
        capital: {
    		type: Number,
    		required: true
    	},
        naf: {
    		type: String,
    		required: true
    	},
        adress: {
    		type: String,
    		required: true
    	},
        cp: {
    		type: Number,
    		required: true
    	},
        city: {
    		type: String,
    		required: true
    	},
        nb_part: {
    		type: Number,
    		required: true
    	},
        associes:[{
            nom: {
        		type: String,
        		required: true,
        	},
            prenom: {
        		type: String,
        		required: true
        	},
            address: {
        		type: String,
        		required: true
        	},
            cp : {
                type: Number,
                required: true
            },
            city: {
                type: String,
                required: true
            },
            birthday: {
                type: Date,
                required: true
            },
            city_birthday: {
                type: String,
                required: true
            },
            np_part: {
                type: Number,
                required: true
            },
            percent_part: {
                type: Number,
                required: true
            }
        }]
    }
```

and when get the data i have this error 
```
/Users/lionelbertrand/Documents/locloud/backfront/node_modules/restberry-mongoose/lib/index.js:107
        } else if (field.caster && field.caster.options.ref) {

TypeError: Cannot read property 'ref' of undefined
    at RestberryMongoose.getFieldsOfModels (/Users/lionelbertrand/Documents/locloud/backfront/node_modules/restberry-mongoose/lib/index.js:107:56)
    at RestberryModel.getFieldsOfModels (/Users/lionelbertrand/Documents/locloud/backfront/node_modules/restberry/lib/model.js:160:24)
    at RestberryModel.getFieldNamesOfModel (/Users/lionelbertrand/Documents/locloud/backfront/node_modules/restberry/lib/model.js:164:10)
    at RestberryObj.__isAuthorized (/Users/lionelbertrand/Documents/locloud/backfront/node_modules/restberry/lib/obj.js:30:20)
    at RestberryObj.isAuthorized (/Users/lionelbertrand/Documents/locloud/backfront/node_modules/restberry/lib/obj.js:110:18)
    at RestberryObj.toJSON (/Users/lionelbertrand/Documents/locloud/backfront/node_modules/restberry/lib/obj.js:249:10)
    at utils.forEachAndDone.json (/Users/lionelbertrand/Documents/locloud/backfront/node_modules/restberry/lib/objs.js:34:13)
    at Object.module.exports.forEachAndDone (/Users/lionelbertrand/Documents/locloud/backfront/node_modules/restberry/node_modules/restberry-utils/lib/index.js:55:13)
    at RestberryObjs.toJSON (/Users/lionelbertrand/Documents/locloud/backfront/node_modules/restberry/lib/objs.js:33:11)
    at /Users/lionelbertrand/Documents/locloud/backfront/node_modules/restberry/node_modules/restberry-router-crud/lib/controller.js:97:26
    at Promise.<anonymous> (/Users/lionelbertrand/Documents/locloud/backfront/node_modules/restberry/lib/model.js:85:13)
    at Promise.<anonymous> (/Users/lionelbertrand/Documents/locloud/backfront/node_modules/restberry-mongoose/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.emit (events.js:107:17)
    at Promise.emit (/Users/lionelbertrand/Documents/locloud/backfront/node_modules/restberry-mongoose/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/Users/lionelbertrand/Documents/locloud/backfront/node_modules/restberry-mongoose/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
    at /Users/lionelbertrand/Documents/locloud/backfront/node_modules/restberry-mongoose/node_modules/mongoose/lib/query.js:1058:26
```

**Comment by materik** [comment]
@lobor I will take a look at this!!

**Comment by materik** [comment]
@lobor Would you mind clearing the node_modules folder and install it again. See if my fix worked for you.

**Comment by lobor** [comment]
Yes, thanks, this work

**Comment by materik** [comment]
Awesome!
